schema_version = "1.0.0"

id = "vrm"
version = "3.16.0"

name = "VRM format"
tagline = "VRM import, export and editing capabilities"
maintainer = "Mizu"
type = "add-on"


tags = ["Import-Export", "Animation", "Modeling", "Material", "Physics"]

blender_version_min = "4.2.0"
blender_version_max = "5.0.0"

license = ["SPDX:MIT", "SPDX:GPL-3.0-or-later"]

copyright = [
  "2025 Mizu"
  "2020 Isamu Mogi",
  "2018 iCyP",
]

[permissions]
files = "Import/export VRM from/to disk"
