[project]
name = "io-scene-vrm-benchmarks"
version = "3.15.0"
readme = "README.md"
requires-python = "==3.10.*" # I actually want to use 3.9, but bpy 3.6.* doesn't allow it.
dependencies = [
  "io-scene-vrm",
  "pytest ==8.4.2",
  "pytest-codspeed ==4.0.0",
]

[tool.uv.sources]
io-scene-vrm = {workspace = true}

[tool.ruff]
extend = "../pyproject.toml"

[tool.ruff.lint]
extend-ignore = [
  "S101", # Use of `assert` detected
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
